[package]
name = "logic"
version = "0.1.0"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
edition = "2018"

[dependencies]
gdnative = "0.9"
rapier2d = "0.7"

[lib]
crate-type = ["cdylib","staticlib"]